[package]
name = "set"
version = "0.1.0"
authors = ["Raphaël Proust <code@bnwr.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "0.7.0"
